### ISSUE TITLE
Feature: add prove server mode

### ISSUE THREAD

**Issue by lispc** [Fluidex/plonkit#19]
##  Feature
Run plonkit  as a server process, so client can send witness to this server, then this server calculates a proof and returns it to the client.

## How 

1. add a new feature flag, 'server'. All the following stuff lives under this flag. (Default: false)
2. add a grpc definition with the [following two APIs](#API). 
3. Add a new command, `server`. This cmd has similar cmd arguments like `prove`, except witness / proof / proofjson / publicjson ( They are all API inputs and outputs). This command behave like following ( you can have a look at `prove` command first ) :
   1. Preload a local r1cs circuit ( filename from cmd flag) ,  with `witness` set to None. 
   2. Then `prepare_setup_for_prover`. 
   3. Then start the grpc server. 
   4. For every API call, set the `witness` field of the circuit, then call [prove](https://github.com/Fluidex/plonkit/blob/4b113b34aa547dd8e645d0498c5522a0dce8dcbe/src/main.rs#L243). 

 Remember the `setup` object is reused between every API call. 

prove function uses every cpu core, so I think requests should be handled one by one. So (n+1)-th request can be processed only after n-th request is finished.

### Prove

Input {
   task_name: String, // log::debug this task_name
   witness: bytes
}
Output {
  is_valid: boolean, 
  error_msg: string, // empty when everything is ok
  time_cost: f64, # time cost in seconds
  proof: Array\<bigint as string\>,
  inputs: Array\<bigint as string\>
}

is_valid is calculated from [is_satisfied_using_one_shot_check](https://github.com/Fluidex/plonkit/blob/4b113b34aa547dd8e645d0498c5522a0dce8dcbe/src/plonk.rs#L104). error_msg is any error encountered. 
proof and input are from [bellman_vk_codegen::serialize_proof](https://github.com/Fluidex/plonkit/blob/4b113b34aa547dd8e645d0498c5522a0dce8dcbe/src/main.rs#L250)

### ValidateWitness
similar to `Prove`. But only [check is_valid ](https://github.com/Fluidex/plonkit/blob/4b113b34aa547dd8e645d0498c5522a0dce8dcbe/src/plonk.rs#L104)

Output may either be {is_valid: true, error_msg: ''} or {is_valid: false, error_msg: 'XXXX'} 

### Status

client can use this API to check whether the server is idle or not.  

Response {
  available: bool,
  current_task_name: String
}

**Comment by lispc** [comment]
Maybe in the future we can seperate this into a new repo ( and make plonkit as a lib ) . But for now it is ok just writing codes in this repo.

**Comment by HAOYUatHZ** [comment]
closed via https://github.com/Fluidex/plonkit/pull/21
