### ISSUE TITLE
 thread 'main' panicked at 'capacity overflow' (plonkit prove)

### ISSUE THREAD

**Issue by apianmuse** [Fluidex/plonkit#61]
I use the following command to generate `witness.wtns` (7.67KB)
```
snarkjs wtns calculate circuit.wasm input.json witness.wtns
```
`circuit_final.zkey`(3.54KB) come from [snarkjs](https://github.com/iden3/snarkjs)

i got an error 
```
$ plonkit prove --srs_monomial_form circuit_final.zkey --circuit circuit.r1cs --witness witness.wtns --proof proof.bin
[2021-05-17T11:55:13Z INFO  plonkit] Loading circuit from circuit.r1cs...
[2021-05-17T11:55:13Z INFO  plonkit::reader] wtns version 2
[2021-05-17T11:55:13Z INFO  plonkit::reader] witness len 243
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:537:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: alloc::raw_vec::capacity_overflow
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/raw_vec.rs:537:5
   4: bellman_ce::kate_commitment::Crs<E,T>::read
   5: plonkit::reader::load_key_monomial_form
   6: plonkit::main

```

The experiment runs on linux

Why does this problem occur?
how to solve this problem?

**Comment by lispc** [comment]
can you give us a repo containing your circuit code and input so we can reproduce this problem?

**Comment by HAOYUatHZ** [comment]
Hi @apianmuse , circuit_final.zkey is not compatible with srs_monomial_form.

So you could download from https://universal-setup.ams3.digitaloceanspaces.com/setup_2^20.key (This file is generated by matter-labs parsing from aztec's setup ceremony, see https://github.com/matter-labs/bellman/blob/f551a55d83d2ea604b2dbfe096fd9dcfdaedb189/src/kate_commitment/mod.rs#L1091 )

Or you can setup one locally by running 
```
plonkit setup --power 20 --srs_monomial_form setup_2^20.key
```

You can take a look at `test/test_poseidon_plonk.sh` as an example.

**Comment by apianmuse** [comment]
> Hi @apianmuse , circuit_final.zkey is not compatible with srs_monomial_form.
> 
> You could either download from [https://universal-setup.ams3.digitaloceanspaces.com/setup_2^20.key](https://universal-setup.ams3.digitaloceanspaces.com/setup_2%5E20.key) (This file is generated by matter-labs parsing from aztec's setup ceremony, see https://github.com/matter-labs/bellman/blob/f551a55d83d2ea604b2dbfe096fd9dcfdaedb189/src/kate_commitment/mod.rs#L1091 )
> 
> Or you could setup one locally by running
> 
> ```
> plonkit setup --power 20 --srs_monomial_form setup_2^20.key
> ```
> 
> You can take a look at `test/test_poseidon_plonk.sh` as an example.

thanks for your help!
