### ISSUE TITLE
How to use plonkit to verify proof for given public inputs?

### ISSUE THREAD

**Issue by bitcartel** [Fluidex/plonkit#8]
After calling `plonkit prove` I have proof.bin, proof.json, public.json.

Public.json contains the public inputs and the public output of the circuit, correct? So how I can verify the proof is valid for that public data? That is, if i change the public inputs the proof should fail verification.

I'm envisaging something similar to this:
`snarkjs groth16 verify verification_key.json public.json proof.json`
e.g.
`plonkit verify vk.bin public.json proof.json`

But current verification only requires proof.bin, e.g. `plonkit verify proof.bin vk.bin'. What is stored in proof.bin? Does it already contain the public inputs and outputs too? Thanks.

**Comment by lispc** [comment]
Yes. 

Proof.bin contains both proof and input. These two *.json are mainly used for ETH contract.

Welcome to our tech telegram group~ <https://t.me/fluid_dex>
